language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
 - chmod +x ./tests/PartitionnerTest.php
script: phpunit --configuration phpunit_config.xml --coverage-text
notifications:
  on_success: never
  on_failure: always