language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
script: ./tests/PartitionnerTest.php
notifications:
  on_success: never
  on_failure: always